### ISSUE TITLE
vault-storage/core/lock#1537560657275741...  

### ISSUE THREAD

**Issue by brettcurtis** [sethvargo/vault-on-gke#14] opened 2018-10-03 15:09 UTC
I've been running an instance of this for a bit now and went to destroy one of my projects and the bucket is full of these lock files. `vault-storage/core/lock#1537560657275741...  ` I've been deleting them for about 30 minutes now and it's still going. This env has been up and running for a week but not being used.

It's not normal I would destroy an instance we've had up and running for sometime so my question is what are these and is this expected? If so anyway I can speed up the process?

**Comment by sethvargo** [comment] 2018-10-03 15:46
Hi @brettcurtis 

This is a dupe of https://github.com/sethvargo/vault-on-gke/issues/13, which has been fixed in master. Basically we were retaining an infinite number of object versions. That's now fixed, but unfortunately there's nothing you can do in the short term besides manually disabling object versioning on the lock in the UI.

> what are these and is this expected?

This is the lock file. It tells Vault which server is the leader. Every so often, the active leader updates this file's timestamp to indicate that it's still healthy and the leader. That's what creates so many versions.

> If so anyway I can speed up the process?

It won't happen again. We added a bucket lifecycle rule to make sure that only the past 3 versions are kept. Sorry!

**Closed as completed by sethvargo** 2018-10-03 15:46 UTC

**Comment by brettcurtis** [comment] 2018-10-03 16:14
Bah, sorry for the dupe - I see what you did and will update. Thanks !
