### ISSUE TITLE
GKE metadata-agent crashloop using the Stackdriver Logging/Monitoring v2(beta) version api logging.googleapis.com/kubernetes

### ISSUE THREAD

**Issue by vdamianchicon** [sethvargo/vault-on-gke#45] opened 2019-03-15 14:19 UTC
**What did you expect to happen?**
Describe what you expected to happen here.
metadata-agent not to crashloop
**What actually happened?**
Describe what actually happened here.
Vault: kube-system - PodFrequentlyRestarting
Pod /metadata-agent-v7hrn is was restarted 10.084033613445378 times within the last hour
Pod /metadata-agent-hzpnq is was restarted 10.084033613445378 times within the last hour
Pod /metadata-agent-cluster-level-579ffb7c5f-6ck7w is was restarted 10.084033613445378 times within the last hour
Pod /metadata-agent-79k7h is was restarted 10.084033613445378 times within the last hour

**Output**
```Metadata request unsuccessful: Server responded with 'Forbidden' (403): Transport endpoint is not connected
What is the output?
```
stackdriver log
**Additional context**

**Comment by sethvargo** [comment] 2019-03-15 14:26
Duplicate of https://github.com/Stackdriver/metadata-agent/issues/142. This is expected behavior according to upstream

**Closed as completed** 2019-03-15 19:05 UTC
